import { useEffect,useState } from 'react'
import { api,message } from './api'

type User={id:string;name:string;email:string;role:string;status:string;customer:{id:string;name:string}}
const roleLabel:any={admin:'Administrador',manager:'Gestor',finance:'Financeiro',user:'Usuário'}
const statusLabel:any={1:'Novo',2:'Em atendimento',3:'Planejado',4:'Pendente',5:'Solucionado',6:'Fechado'}

function Brand(){return <div className="brand"><div className="mark">V</div><div><h1>Portal do Cliente</h1><p>VGON Tecnologia</p></div></div>}

function Auth({onLogin}:{onLogin:(u:User)=>void}){
 const [mode,setMode]=useState<'login'|'register'>('login'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
 const [form,setForm]=useState<any>({cnpj:'',name:'',email:'',phone:'',department:'',password:''})
 async function submit(e:any){e.preventDefault();setBusy(true);setError('');setNotice('');try{if(mode==='login'){const r=await api.post('/portal/public/login',form);localStorage.setItem('portal_user',JSON.stringify(r.data.user));onLogin(r.data.user)}else{const r=await api.post('/portal/public/register',form);setNotice(r.data.message);setMode('login')}}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <main className="auth"><form className="auth-card" onSubmit={submit}><Brand/><h2>{mode==='login'?'Acesse sua empresa':'Solicite seu acesso'}</h2><p className="muted">{mode==='login'?'Acompanhe chamados, SLA e documentos.':'Seu cadastro será aprovado pelo administrador da empresa.'}</p>
 {mode==='register'&&<><div className="field"><label>CNPJ da empresa</label><input className="input" value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})} required/></div><div className="field"><label>Nome completo</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div className="field"><label>Telefone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Setor</label><input className="input" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></div></>}
 <div className="field"><label>E-mail</label><input type="email" className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div className="field"><label>Senha</label><input type="password" minLength={8} className="input" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></div>
 {error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}<button className="btn primary wide" disabled={busy}>{busy?'Aguarde...':mode==='login'?'Entrar':'Enviar para aprovação'}</button><p className="muted" style={{textAlign:'center'}}><button type="button" className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Ainda não tenho acesso':'Já tenho cadastro'}</button></p></form></main>
}

export default function App(){
 const [user,setUser]=useState<User|null>(()=>{try{return JSON.parse(localStorage.getItem('portal_user')||'null')}catch{return null}}),[tab,setTab]=useState('dashboard')
 useEffect(()=>{if(user)api.get('/portal/me').then(r=>setUser(r.data)).catch(()=>{setUser(null);localStorage.removeItem('portal_user')})},[])
 if(!user)return <Auth onLogin={setUser}/>
 async function logout(){await api.post('/portal/public/logout');localStorage.removeItem('portal_user');setUser(null)}
 const tabs=[['dashboard','Visão geral'],['tickets','Chamados'],...(['admin','finance'].includes(user.role)?[['documents','Financeiro e contratos']]:[]),...(user.role==='admin'?[['users','Usuários']]:[])]
 return <div className="shell"><aside className="side"><Brand/><div className="nav">{tabs.map((x:any)=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}<button onClick={logout}>Sair</button></div></aside><main className="content"><header className="top"><div><h2>{tabs.find((x:any)=>x[0]===tab)?.[1]}</h2><span className="muted">{user.customer.name}</span></div><div><strong>{user.name}</strong><div className="muted">{roleLabel[user.role]}</div></div></header>{tab==='dashboard'&&<Dashboard/>}{tab==='tickets'&&<Tickets user={user}/>} {tab==='documents'&&<Documents/>}{tab==='users'&&<Users/>}</main></div>
}

function Dashboard(){const [data,setData]=useState<any>();useEffect(()=>{api.get('/portal/dashboard').then(r=>setData(r.data))},[]);if(!data)return <p>Carregando...</p>;const remaining=Math.max(0,data.sla.included-data.sla.consumed);return <div className="grid"><div className="card metric"><span className="muted">Chamados abertos</span><strong>{data.tickets.open}</strong></div><div className="card metric"><span className="muted">SLA utilizado no mês</span><strong>{data.sla.consumed.toFixed(1)}h</strong></div><div className="card metric"><span className="muted">SLA restante</span><strong>{remaining.toFixed(1)}h</strong></div><div className="card metric"><span className="muted">Horas excedentes</span><strong>{data.sla.exceeded.toFixed(1)}h</strong></div><div className="card span2"><h3>Franquia mensal</h3><p className="muted">Competência {data.sla.month}</p><progress style={{width:'100%'}} max={Math.max(data.sla.included,1)} value={Math.min(data.sla.consumed,data.sla.included)}/><p>{data.sla.consumed.toFixed(1)}h de {data.sla.included.toFixed(1)}h</p></div><div className="card span2"><h3>Resumo</h3><p>{data.tickets.total} chamados registrados pelo portal</p><p>{data.contracts} contrato(s) ativo(s)</p>{data.sla.charge>0&&<p><strong>Excedente estimado: R$ {data.sla.charge.toFixed(2)}</strong></p>}</div></div>}

function Tickets({user}:{user:User}){const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[form,setForm]=useState<any>({title:'',description:'',type:1,urgency:3});const load=()=>api.get('/portal/tickets').then(r=>setRows(r.data));useEffect(()=>{void load()},[]);async function submit(e:any){e.preventDefault();setBusy(true);setError('');try{await api.post('/portal/tickets',form);setOpen(false);setForm({title:'',description:'',type:1,urgency:3});load()}catch(e){setError(message(e))}finally{setBusy(false)}}return <><div className="actions" style={{marginBottom:16}}><button className="btn primary" onClick={()=>setOpen(!open)}>+ Abrir chamado</button></div>{open&&<form className="card" onSubmit={submit}><h3>Novo chamado</h3><div className="form-grid"><div className="field full"><label>Assunto</label><input className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></div><div className="field full"><label>Descrição detalhada</label><textarea rows={5} className="input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></div><div className="field"><label>Tipo</label><select className="input" value={form.type} onChange={e=>setForm({...form,type:Number(e.target.value)})}><option value="1">Incidente</option><option value="2">Requisição</option></select></div><div className="field"><label>Urgência</label><select className="input" value={form.urgency} onChange={e=>setForm({...form,urgency:Number(e.target.value)})}><option value="1">Baixa</option><option value="3">Média</option><option value="5">Alta</option></select></div></div>{error&&<p className="error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Enviando ao GLPI...':'Criar chamado'}</button></form>}<div className="card table-wrap" style={{marginTop:16}}><table className="table"><thead><tr><th># GLPI</th><th>Assunto</th>{user.role!=='user'&&<th>Solicitante</th>}<th>Status</th><th>Abertura</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>#{x.glpiTicketId}</td><td>{x.title}</td>{user.role!=='user'&&<td>{x.requester?.name}</td>}<td><span className="badge">{statusLabel[x.status]||x.status}</span></td><td>{new Date(x.createdAt).toLocaleString('pt-BR')}</td></tr>)}</tbody></table>{!rows.length&&<p className="muted">Nenhum chamado aberto pelo portal.</p>}</div></>}

function Documents(){const [data,setData]=useState<any>();useEffect(()=>{api.get('/portal/documents').then(r=>setData(r.data))},[]);if(!data)return <p>Carregando...</p>;return <div className="grid"><section className="card span2 table-wrap"><h3>Boletos e contas a receber</h3><table className="table"><thead><tr><th>Descrição</th><th>Vencimento</th><th>Status</th><th>Valor</th></tr></thead><tbody>{data.receivables.map((x:any)=><tr key={x.id}><td>{x.description}</td><td>{x.dueDate}</td><td>{x.status}</td><td>R$ {Number(x.totalValue).toFixed(2)}</td></tr>)}</tbody></table></section><section className="card span2 table-wrap"><h3>Notas fiscais</h3><table className="table"><thead><tr><th>Número</th><th>Tipo</th><th>Status</th><th>Valor</th></tr></thead><tbody>{data.invoices.map((x:any)=><tr key={x.id}><td>{x.number||'-'}</td><td>{x.type}</td><td>{x.status}</td><td>R$ {Number(x.totalValue).toFixed(2)}</td></tr>)}</tbody></table></section><section className="card span2"><h3>Contratos</h3>{data.contracts.map((x:any)=><p key={x.id}><strong>{x.title}</strong><br/><span className="muted">SLA: {Number(x.slaTotalHours).toFixed(1)}h • {x.status}</span></p>)}</section></div>}

function Users(){const [rows,setRows]=useState<any[]>([]),[form,setForm]=useState<any>({name:'',email:'',password:'',role:'user'}),[error,setError]=useState('');const load=()=>api.get('/portal/users').then(r=>setRows(r.data));useEffect(()=>{void load()},[]);async function create(e:any){e.preventDefault();try{await api.post('/portal/users',form);setForm({name:'',email:'',password:'',role:'user'});load()}catch(e){setError(message(e))}}async function status(id:string,value:string){await api.patch('/portal/users/'+id,{status:value});load()}return <div className="grid"><form className="card" onSubmit={create}><h3>Adicionar funcionário</h3>{['name','email','password'].map(k=><div className="field" key={k}><label>{{name:'Nome',email:'E-mail',password:'Senha provisória'}[k]}</label><input className="input" type={k==='password'?'password':k==='email'?'email':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required/></div>)}<div className="field"><label>Permissão</label><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="user">Usuário</option><option value="manager">Gestor</option><option value="finance">Financeiro</option><option value="admin">Administrador</option></select></div>{error&&<p className="error">{error}</p>}<button className="btn primary">Criar usuário</button></form><section className="card span2 table-wrap"><h3>Usuários da empresa</h3><table className="table"><thead><tr><th>Nome</th><th>Perfil</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}<div className="muted">{x.email}</div></td><td>{roleLabel[x.role]}</td><td>{x.status}</td><td>{x.status==='pending'&&<button className="btn secondary" onClick={()=>status(x.id,'active')}>Aprovar</button>} {x.status==='active'&&<button className="btn danger" onClick={()=>status(x.id,'blocked')}>Bloquear</button>}{x.status==='blocked'&&<button className="btn secondary" onClick={()=>status(x.id,'active')}>Ativar</button>}</td></tr>)}</tbody></table></section></div>}
