import { useEffect, useState } from 'react';
import { Plus, TrendingUp } from 'lucide-react';
import { api } from '../services/api';
import { useFeedback } from '../components/ui';
const stages=[['lead','Lead'],['contato','Contato'],['proposta','Proposta'],['negociacao','Negociação'],['ganho','Ganho'],['perdido','Perdido']];
export function Crm(){const { notify }=useFeedback();const [items,setItems]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState<any>({title:'',stage:'lead',value:'',probability:10,customerId:'',expectedCloseDate:''});
 const load=async()=>{try{const [a,c]=await Promise.all([api.get('/crm/opportunities'),api.get('/customers')]);setItems(a.data);setCustomers(c.data)}catch{notify('Não foi possível carregar o CRM','error')}};useEffect(()=>{load()},[]);
 const save=async(e:any)=>{e.preventDefault();try{await api.post('/crm/opportunities',{...form,value:Number(form.value||0),probability:Number(form.probability)});setOpen(false);setForm({title:'',stage:'lead',value:'',probability:10,customerId:'',expectedCloseDate:''});load();notify('Oportunidade criada','success')}catch(e:any){notify(e.response?.data?.message||'Erro ao salvar','error')}};
 const move=async(id:string,stage:string)=>{let lostReason:any=undefined;if(stage==='perdido'){lostReason=prompt('Motivo da perda:');if(!lostReason)return}await api.patch('/crm/opportunities/'+id,{stage,lostReason});load()};
 const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">CRM de oportunidades</h1><p className="text-sm text-gray-500">Funil comercial e previsão de fechamento</p></div><button className="btn btn-primary flex gap-2" onClick={()=>setOpen(true)}><Plus className="w-4"/>Nova oportunidade</button></div><div className="grid grid-cols-1 md:grid-cols-3 xl:grid-cols-6 gap-3 overflow-x-auto">{stages.map(([key,label])=><section key={key} className="card p-3 min-h-64"><div className="flex justify-between mb-3"><h2 className="font-semibold">{label}</h2><span className="badge">{items.filter(x=>x.stage===key).length}</span></div><div className="space-y-2">{items.filter(x=>x.stage===key).map(x=><article key={x.id} className="rounded-lg border p-3 bg-white dark:bg-gray-800"><p className="font-medium text-sm">{x.title}</p><p className="text-xs text-gray-500">{x.customer?.name||x.contactName||'Sem cliente'}</p><p className="mt-2 font-semibold text-sm">{money(x.value)}</p><p className="text-xs text-gray-500"><TrendingUp className="inline w-3"/> {x.probability}%</p><select aria-label="Mover etapa" value={x.stage} onChange={e=>move(x.id,e.target.value)} className="input mt-2 text-xs">{stages.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></article>)}</div></section>)}</div>{open&&<div className="modal-overlay"><form onSubmit={save} className="modal-content max-w-xl space-y-3"><h2 className="text-xl font-bold">Nova oportunidade</h2><input className="input" required placeholder="Título" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className="input" value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">Cliente ainda não cadastrado</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input className="input" type="number" min="0" step="0.01" placeholder="Valor" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/><input className="input" type="number" min="0" max="100" placeholder="Probabilidade %" value={form.probability} onChange={e=>setForm({...form,probability:e.target.value})}/><input className="input" type="date" value={form.expectedCloseDate} onChange={e=>setForm({...form,expectedCloseDate:e.target.value})}/></div><div className="flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn btn-primary">Salvar</button></div></form></div>}</div>}
