import { useEffect,useState } from 'react'
import { ExternalLink,Plus,ShieldCheck,Users } from 'lucide-react'
import { api } from '../services/api'

const empty={customerId:'',name:'',email:'',password:'',role:'admin'}
export function CustomerPortalAdmin(){
 const [users,setUsers]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[error,setError]=useState(''),[saving,setSaving]=useState(false),[formCustomer,setFormCustomer]=useState(''),[fields,setFields]=useState(`Assunto|text|obrigatorio\nDescrição|textarea|obrigatorio\nTipo|select|obrigatorio\nUrgência|select|obrigatorio`)
 const load=async()=>{const [u,c]=await Promise.all([api.get('/portal/admin/users'),api.get('/customers')]);setUsers(u.data);setCustomers(c.data)}
 useEffect(()=>{load().catch(()=>setError('Não foi possível carregar a administração do portal'))},[])
 async function create(e:any){e.preventDefault();setSaving(true);setError('');try{await api.post('/portal/admin/users',form);setForm(empty);await load()}catch(e:any){setError(e.response?.data?.message||'Erro ao criar usuário')}finally{setSaving(false)}}
 async function update(id:string,status:string){await api.patch('/portal/admin/users/'+id,{status});load()}
 async function saveTicketForm(){const parsed=fields.split(/\n/).filter(Boolean).map((line,i)=>{const [label,type,required]=line.split('|');return {key:'field_'+i,label,type:type||'text',required:required==='obrigatorio'}});await api.post('/portal/admin/forms',{name:'Formulário de abertura',customerId:formCustomer||null,active:true,fields:parsed});alert('Formulário salvo com sucesso')}
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-900">Portal do cliente</h1><p className="text-sm text-gray-500">Superadministração de empresas, usuários e formulários.</p></div><a href="https://portal.vgon.com.br" target="_blank" rel="noreferrer" className="btn btn-secondary inline-flex items-center gap-2"><ExternalLink className="h-4 w-4"/>Abrir portal</a></div>
 <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><form className="card space-y-4" onSubmit={create}><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary-600"/><h2 className="font-semibold">Criar administrador</h2></div><div><label className="form-label">Cliente / empresa</label><select className="input" value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})} required><option value="">Selecione</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} — {c.cpfCnpj||'sem CNPJ'} {c.glpiEntityId?`(GLPI ${c.glpiEntityId})`:'(sem entidade)'}</option>)}</select></div><div><label className="form-label">Nome</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div><label className="form-label">E-mail</label><input type="email" className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div><label className="form-label">Senha provisória</label><input type="password" minLength={8} className="input" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></div><div><label className="form-label">Perfil</label><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="admin">Administrador da empresa</option><option value="manager">Gestor</option><option value="finance">Financeiro</option><option value="user">Usuário comum</option></select></div>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={saving} className="btn btn-primary flex w-full items-center justify-center gap-2"><Plus className="h-4 w-4"/>{saving?'Criando...':'Criar acesso'}</button></form>
 <section className="card overflow-hidden p-0"><div className="flex items-center gap-2 border-b p-5"><Users className="h-5 w-5 text-primary-600"/><h2 className="font-semibold">Usuários cadastrados</h2></div><div className="overflow-x-auto"><table className="table"><thead className="table-header"><tr><th className="table-cell">Usuário</th><th className="table-cell">Empresa</th><th className="table-cell">Perfil</th><th className="table-cell">Status</th><th className="table-cell">Ações</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td className="table-cell"><p className="font-medium">{u.name}</p><p className="text-xs text-gray-500">{u.email}</p></td><td className="table-cell">{u.customer?.name||'-'}</td><td className="table-cell">{u.role}</td><td className="table-cell">{u.status}</td><td className="table-cell"><div className="flex gap-2">{u.status!=='active'&&<button className="text-sm font-medium text-green-600" onClick={()=>update(u.id,'active')}>Aprovar/ativar</button>}{u.status==='active'&&<button className="text-sm font-medium text-red-600" onClick={()=>update(u.id,'blocked')}>Bloquear</button>}</div></td></tr>)}</tbody></table></div></section></div><section className="card"><h2 className="mb-1 font-semibold">Configurar formulário de abertura</h2><p className="mb-4 text-sm text-gray-500">Sem cliente selecionado, o formulário será o padrão para todas as empresas. Use uma linha por campo: Nome|tipo|obrigatorio.</p><div className="grid gap-4 md:grid-cols-[280px_1fr_auto]"><select className="input" value={formCustomer} onChange={e=>setFormCustomer(e.target.value)}><option value="">Padrão para todas as empresas</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea className="input min-h-32 font-mono text-xs" value={fields} onChange={e=>setFields(e.target.value)}/><button type="button" onClick={saveTicketForm} className="btn btn-primary self-start">Salvar formulário</button></div></section></div>
}
