import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { BookOpen, Search, ChevronRight, ExternalLink, Lightbulb, ShieldAlert } from 'lucide-react'
import { PageHeader } from '../components/ui'

interface Guide {
  id: string
  category: string
  title: string
  route?: string
  summary: string
  prerequisites?: string[]
  steps: string[]
  result: string
  notes?: string[]
  keywords: string
}

const guides: Guide[] = [
  { id:'primeiros-passos', category:'Introdução', title:'Primeiros passos e navegação', summary:'Entenda o menu, os perfis de acesso, a pesquisa e as notificações.', steps:['Entre com seu usuário e confirme seu nome e perfil no rodapé do menu lateral.','Abra um grupo do menu; apenas um grupo permanece expandido para facilitar a navegação.','Use o sino no topo para consultar contas vencidas, rejeições fiscais, estoque baixo e aprovações.','Clique em uma notificação para abrir diretamente o módulo relacionado; use o ícone de confirmação para resolvê-la.','Acesse seu nome no rodapé para revisar os dados do perfil.'], result:'Você consegue localizar módulos, identificar pendências e navegar conforme as permissões do seu perfil.', notes:['Administrador possui acesso integral; Financeiro acessa rotinas comerciais, financeiras e fiscais; Técnico visualiza apenas rotinas liberadas.'], keywords:'começar inicio menu perfil acesso sino notificações navegação' },
  { id:'clientes', category:'Comercial e vendas', title:'Cadastrar e preparar um cliente', route:'/customers', summary:'Cadastre dados comerciais e fiscais necessários para vendas, boletos e notas.', prerequisites:['Tenha CPF/CNPJ, endereço, CEP, telefone e e-mail do cliente.'], steps:['Abra Comercial e vendas > Clientes.','Clique em Novo cliente.','Informe nome ou razão social, CPF/CNPJ, telefone e e-mail.','Preencha endereço, bairro, cidade, UF, CEP e inscrição estadual quando aplicável.','Registre observações úteis e mantenha o cadastro ativo.','Salve e confira se o cliente aparece na listagem.','Consulte Administração > Controles do ERP > Qualidade para localizar informações fiscais ausentes.'], result:'O cliente fica disponível para orçamentos, vendas, faturamento, boleto e envio de documentos.', notes:['O e-mail é obrigatório para o envio do pacote de nota, XML e boleto.','Dados fiscais incompletos podem provocar rejeição da nota.'], keywords:'cliente cadastro cnpj cpf endereço email inscrição estadual dados incompletos' },
  { id:'produtos-servicos', category:'Catálogo e estoque', title:'Cadastrar produtos e serviços', route:'/products', summary:'Configure itens com preço, tributação e dados fiscais.', steps:['Abra Catálogo e estoque > Produtos ou Serviços.','Clique em adicionar e informe código único, nome, categoria e descrição.','Para produtos, informe custo, preço de venda, estoque mínimo e quantidade inicial.','Preencha NCM, CFOP, CEST e unidade conforme orientação contábil.','Indique se o produto exige controle de lote ou número de série.','Para serviços, configure descrição, valor e código municipal quando utilizado na NFS-e.','Salve e valide o cadastro antes de incluir o item em uma venda.'], result:'O item pode ser selecionado em orçamento, venda, estoque, compra e emissão fiscal.', notes:['Não escolha NCM, CFOP ou tributação por suposição; valide com a contabilidade.'], keywords:'produto serviço ncm cfop cest preço custo unidade imposto cadastro' },
  { id:'orcamento', category:'Comercial e vendas', title:'Criar e aprovar um orçamento', route:'/orcamentos', summary:'Monte uma proposta antes de gerar a venda definitiva.', prerequisites:['Cliente e produtos ou serviços cadastrados.'], steps:['Abra Comercial e vendas > Orçamentos.','Crie um orçamento e selecione o cliente.','Inclua produtos e serviços, ajustando quantidades e valores permitidos.','Informe condições comerciais, validade e observações.','Revise subtotal, descontos, impostos e total.','Salve como rascunho enquanto estiver em negociação.','Após aceite do cliente, aprove o orçamento e converta-o em venda.'], result:'A negociação fica registrada e pode originar uma venda sem redigitação.', notes:['Aprovar orçamento não significa que a nota ou o boleto já foram emitidos.'], keywords:'orçamento proposta aprovação converter venda desconto validade' },
  { id:'venda', category:'Comercial e vendas', title:'Registrar uma venda completa', route:'/sales/new', summary:'Crie uma venda, configure pagamento e acompanhe todo o ciclo.', prerequisites:['Cliente válido e itens cadastrados.'], steps:['Abra Comercial e vendas > Vendas e clique em Nova venda.','Selecione cliente e responsável técnico ou comercial.','Adicione itens e confira quantidade, preço, tributos e disponibilidade em estoque.','Informe desconto; quando ultrapassar a regra interna, solicite autorização.','Escolha forma de pagamento, parcelas, vencimento, multa e mora quando aplicável.','Revise o resumo e confirme a venda.','Acompanhe o histórico de eventos, anexos, aprovação, faturamento e recebimento na venda.'], result:'A venda gera os registros comerciais e financeiros correspondentes e fica pronta para faturamento.', notes:['Não emita documentos antes de conferir cliente, valores e condições de pagamento.'], keywords:'venda nova itens parcelas vencimento desconto aprovação pagamento histórico' },
  { id:'pdv', category:'Comercial e vendas', title:'Realizar venda rápida no PDV', route:'/pdv', summary:'Use o ponto de venda para operações imediatas.', steps:['Abra Comercial e vendas > PDV.','Localize produtos por código ou nome e adicione-os ao atendimento.','Ajuste quantidades e confira o total.','Identifique o cliente quando precisar de documento fiscal, crédito ou fidelidade.','Escolha a forma de pagamento e confirme o recebimento.','Finalize e confira a atualização do estoque e do financeiro.'], result:'A venda rápida é registrada com baixa de estoque e movimentação financeira conforme a forma de pagamento.', keywords:'pdv balcão venda rápida caixa pagamento produto' },
  { id:'estoque', category:'Catálogo e estoque', title:'Movimentar, reservar e consultar estoque', route:'/stock', summary:'Acompanhe posição, entradas, saídas e disponibilidade real.', steps:['Abra Catálogo e estoque > Posição de estoque.','Pesquise o produto e compare quantidade física, reservada e disponível.','Registre entrada para recebimentos e saída para consumo ou correção autorizada.','Informe lote ou série quando o produto exigir rastreabilidade.','Consulte produtos abaixo do estoque mínimo.','Abra Inventário e Kardex para visualizar todo o histórico do item.'], result:'O saldo permanece rastreável e os alertas de reposição aparecem nas notificações.', notes:['Nunca use ajuste sem justificativa; prefira movimentos vinculados a compra, venda ou inventário.'], keywords:'estoque entrada saída reserva saldo mínimo lote série movimento' },
  { id:'inventario', category:'Catálogo e estoque', title:'Realizar inventário e consultar Kardex', route:'/estoque-avancado', summary:'Corrija diferenças físicas com justificativa e mantenha rastreabilidade.', steps:['Abra Catálogo e estoque > Inventário e Kardex.','Selecione o produto contado.','Informe quantidade física e confira a quantidade registrada pelo sistema.','Descreva a justificativa quando existir diferença.','Confirme o inventário para gerar o ajuste auditado.','Use o Kardex para conferir data, origem, usuário, custo e saldo de cada movimento.'], result:'A diferença é corrigida e permanece documentada no histórico do produto.', keywords:'inventário contagem ajuste justificativa kardex histórico custo médio' },
  { id:'compras', category:'Compras', title:'Executar o ciclo de compras', route:'/compras', summary:'Da solicitação ao recebimento, estoque e conta a pagar.', steps:['Abra Compras > Solicitações e compras.','Crie a solicitação com itens, quantidades, necessidade e centro de custo.','Envie para aprovação quando o valor ultrapassar a alçada.','Registre cotações dos fornecedores em Cotações e recebimento.','Compare preço, prazo e condição; selecione a proposta vencedora.','Emita a ordem de compra.','No recebimento, informe as quantidades efetivamente entregues, inclusive recebimento parcial.','Anexe XML e PDF da nota do fornecedor.','Confirme a entrada de estoque e a geração da conta a pagar.'], result:'Compra, estoque, documentos e obrigação financeira permanecem vinculados.', keywords:'compra solicitação cotação fornecedor ordem recebimento parcial xml conta pagar' },
  { id:'financeiro-receber', category:'Financeiro', title:'Acompanhar contas a receber e baixas', route:'/financeiro', summary:'Controle valores previstos, vencidos, parciais e recebidos.', steps:['Abra Financeiro > Visão financeira.','Filtre por período, cliente, status ou forma de pagamento.','Abra a conta e confira competência, vencimento, parcelas e saldo pendente.','Para registrar recebimento, selecione a parcela e informe valor, data, forma e conta bancária.','Em baixa parcial, repita o procedimento a cada pagamento recebido.','Confira o histórico de baixas e a movimentação realizada.','Use estorno formal quando precisar desfazer uma baixa.'], result:'O contas a receber, o fluxo realizado e o saldo da parcela são atualizados.', notes:['Não altere diretamente uma baixa antiga; use estorno para preservar auditoria.'], keywords:'financeiro conta receber baixa parcial parcela pagamento estorno competência' },
  { id:'contas-pagar', category:'Financeiro', title:'Cadastrar e pagar uma conta', route:'/contas-pagar', summary:'Controle fornecedores, vencimentos, competência e aprovação.', steps:['Abra Financeiro > Contas a pagar.','Crie a conta com fornecedor, descrição, valor, competência e vencimento.','Selecione centro de custo, plano de contas e conta bancária prevista.','Anexe ou referencie o documento de origem.','Se o valor exigir alçada, envie para aprovação.','No pagamento, informe data, valor, conta bancária e comprovante.','Confira o lançamento no fluxo de caixa realizado.'], result:'A obrigação passa de prevista para paga com rastreabilidade financeira.', keywords:'conta pagar fornecedor despesa vencimento competência aprovação comprovante' },
  { id:'conciliacao', category:'Financeiro', title:'Importar extrato e conciliar movimentos', route:'/conciliacao', summary:'Compare extrato bancário com os lançamentos do ERP.', prerequisites:['Conta bancária cadastrada e arquivo OFX compatível.'], steps:['Abra Financeiro > Conciliação bancária.','Selecione a conta e importe o arquivo OFX.','Aguarde a identificação automática de possíveis correspondências.','Confira data, valor, descrição e lançamento sugerido.','Confirme a conciliação quando os dados coincidirem.','Vincule manualmente quando não houver sugestão segura.','Crie um movimento somente quando ele realmente não existir no ERP.','Ignore itens que não devam compor o financeiro, registrando o motivo.'], result:'Extrato e movimentos locais ficam vinculados e as divergências permanecem visíveis.', keywords:'conciliação ofx extrato banco movimento importar correspondência' },
  { id:'dre', category:'Financeiro', title:'Analisar DRE e fluxo de caixa', route:'/dre', summary:'Diferencie resultado por competência de disponibilidade de caixa.', steps:['Abra Financeiro > DRE.','Selecione o período de competência.','Confira receitas, deduções, custos, despesas e resultado.','Expanda os grupos para validar as contas contábeis de origem.','Compare com o fluxo de caixa realizado para identificar diferenças de prazo.','Exporte os dados para conferência contábil quando necessário.'], result:'Você obtém o resultado econômico do período sem confundi-lo com entradas e saídas bancárias.', notes:['DRE usa competência; fluxo de caixa usa datas previstas ou realizadas.'], keywords:'dre resultado receita despesa competência fluxo caixa contabilidade' },
  { id:'boleto', category:'Fiscal e bancos', title:'Gerar e acompanhar boleto Banco Inter', route:'/inter-avancado', summary:'Emita, consulte, baixe e concilie cobranças BolePix.', prerequisites:['Credenciais e certificado do Banco Inter configurados; cliente com documento e endereço válidos.'], steps:['Abra a venda e solicite a geração do boleto.','Confira valor, vencimento, pagador, multa e mora antes de confirmar.','Após emissão, consulte Banco Inter para visualizar a situação real.','Baixe o PDF na lista de boletos quando necessário.','O webhook informa pagamentos; a conciliação automática baixa o financeiro.','Use Atualizar status se precisar consultar a API imediatamente.','Para cancelar, execute a baixa real no Inter e confira o status local.'], result:'O boleto fica vinculado à venda e ao financeiro, com situação sincronizada pelo banco.', notes:['A_RECEBER vem da situação consultada no Banco Inter.','Não gere uma segunda cobrança idêntica sem verificar a cobrança existente.'], keywords:'boleto inter bolepix pdf webhook pago a receber cancelar atualizar status' },
  { id:'nfe', category:'Fiscal e bancos', title:'Emitir NF-e ou NFC-e', route:'/fiscal', summary:'Valide, transmita, consulte e armazene documentos de mercadorias.', prerequisites:['Certificado A1 válido; configuração fiscal; cliente e produtos completos.'], steps:['Abra Fiscal e bancos > Notas fiscais.','Selecione NF-e modelo 55 ou NFC-e modelo 65 e confirme o ambiente.','Escolha a venda e o certificado ativo.','Revise emitente, destinatário, NCM, CFOP, CST/CSOSN, valores e totais.','Emita e aguarde autorização; não repita o envio enquanto estiver processando.','Confira chave de acesso, número e protocolo.','Baixe XML e DANFE e consulte o status na SEFAZ.','Em rejeição, abra Operações fiscais, leia o motivo, corrija o cadastro e reenvie pela fila.'], result:'A nota autorizada e seus protocolos ficam armazenados e vinculados à venda.', notes:['Use homologação para testes. Documento em homologação não possui validade fiscal.'], keywords:'nfe nfce sefaz emitir danfe xml protocolo rejeição homologação produção' },
  { id:'nfse', category:'Fiscal e bancos', title:'Emitir NFS-e Cidade360', route:'/fiscal', summary:'Emita nota de serviço para a Prefeitura de Contagem.', prerequisites:['Certificado e configuração da Cidade360; inscrição municipal; serviço e tomador válidos.'], steps:['Abra Fiscal e bancos > Notas fiscais e escolha NFS-e.','Selecione venda e certificado.','Confira código do serviço, município de incidência, descrição e valor.','Revise retenção, ISSQN, PIS, COFINS e campos IBS/CBS aplicáveis.','Emita e aguarde o retorno da Cidade360.','Confira número, código de verificação, protocolo e valor líquido.','Baixe XML e PDF e consulte novamente o status quando necessário.'], result:'A NFS-e autorizada fica vinculada à venda e disponível para envio ao cliente.', notes:['Regras municipais devem ser validadas em homologação antes do uso em produção.'], keywords:'nfse cidade360 contagem iss pis cofins ibs cbs serviço prefeitura' },
  { id:'eventos-fiscais', category:'Fiscal e bancos', title:'Cancelar nota, emitir CC-e e inutilizar numeração', route:'/fiscal-avancado', summary:'Execute eventos fiscais reais com protocolo.', steps:['Abra Fiscal e bancos > Operações fiscais.','Para cancelamento, selecione a nota autorizada, informe justificativa válida e transmita; confira o protocolo.','Para Carta de Correção, selecione a NF-e, descreva claramente a correção permitida e envie à SEFAZ.','Para inutilização, escolha modelo 55 ou 65, certificado, série, faixa inicial/final e justificativa.','Consulte a lista de eventos e tentativas para confirmar status, resposta e protocolo.'], result:'O evento é transmitido ao órgão e registrado na auditoria local.', notes:['CC-e não pode alterar valor do imposto, remetente/destinatário ou data de emissão/saída.','Nunca considere um documento cancelado apenas por uma alteração local; confirme o protocolo oficial.'], keywords:'cancelar nota carta correção cce inutilização numeração protocolo evento fiscal' },
  { id:'email', category:'Administração', title:'Configurar e enviar documentos por e-mail', route:'/email-settings', summary:'Configure SMTP ou Microsoft 365 e envie nota, XML e boleto juntos.', steps:['Abra Administração > Configuração de e-mail.','Escolha SMTP ou Microsoft 365.','No SMTP, informe servidor, porta, segurança, usuário, senha e remetente.','No Microsoft 365, informe Tenant ID, Client ID e o valor do segredo do aplicativo.','Configure o e-mail padrão em cópia, se necessário.','Salve e execute o envio de teste.','Na venda, use Enviar para o cliente para reunir nota, XML e boleto em uma única mensagem.'], result:'O ERP envia documentos pelo remetente configurado e registra o reenvio.', notes:['Para Microsoft 365, use permissão de aplicativo quando o envio for feito sem usuário conectado.','O segredo é o campo Valor; o ID do segredo não autentica.'], keywords:'email smtp microsoft 365 tenant client secret cópia anexo enviar cliente' },
  { id:'notificacoes', category:'Administração', title:'Usar notificações e resolver pendências', summary:'Acompanhe eventos que exigem ação sem depender do dashboard.', steps:['Observe o contador do sino no canto superior direito.','Clique no sino para listar notificações novas e lidas.','Abra uma notificação para marcá-la como lida e ir ao módulo de origem.','Clique no ícone de confirmação do item para resolvê-lo.','Use Marcar todas como lidas apenas quando tiver revisado os avisos.','Abra Controles do ERP para consultar a central completa.'], result:'Pendências ficam distribuídas, acompanhadas e resolvidas de forma rastreável.', keywords:'sino notificação pendência marcar lida resolver alerta' },
  { id:'aprovacoes', category:'Administração', title:'Executar aprovações em duas etapas', route:'/controles-erp', summary:'Aprove estornos e operações de alto valor com segregação.', steps:['Abra Administração > Controles do ERP > Aprovações.','Confira tipo, entidade, valor, justificativa e solicitante.','O primeiro aprovador revisa e registra a primeira etapa.','Um segundo usuário diferente registra a aprovação final.','Rejeite informando o motivo quando a operação não estiver correta.','Consulte a auditoria para verificar solicitante, aprovadores e horários.'], result:'A operação crítica só é liberada após as etapas exigidas.', notes:['O solicitante não pode aprovar a própria solicitação; o primeiro aprovador não pode realizar a segunda aprovação.'], keywords:'aprovação duas etapas alçada estorno pagamento alto valor segregação' },
  { id:'fechamento', category:'Administração', title:'Realizar fechamento financeiro e fiscal', route:'/controles-erp', summary:'Trave períodos concluídos e preserve os relatórios históricos.', steps:['Conclua conciliações, baixas, documentos fiscais e conferências do período.','No Financeiro, execute o fechamento mensal financeiro.','Em Controles do ERP, abra Fechamento fiscal.','Informe o período no formato AAAA-MM e registre observações.','Confirme e verifique o registro do usuário e horário.','Para correções posteriores, siga o processo autorizado de reabertura e auditoria.'], result:'Períodos concluídos ficam identificados separadamente para financeiro e fiscal.', keywords:'fechamento mensal fiscal financeiro período trava reabrir' },
]

const normalize = (value:string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()

export function Tutorial() {
  const [query,setQuery] = useState('')
  const [category,setCategory] = useState('Todos')
  const categories = ['Todos',...Array.from(new Set(guides.map(guide=>guide.category)))]
  const filtered = useMemo(() => {
    const term = normalize(query.trim())
    return guides.filter(guide => (category==='Todos'||guide.category===category) && (!term || normalize(`${guide.title} ${guide.summary} ${guide.keywords} ${guide.steps.join(' ')}`).includes(term)))
  },[query,category])

  return <div className="mx-auto max-w-6xl">
    <PageHeader title="Tutorial do sistema" description="Manual operacional completo do ERP" leading={<BookOpen className="h-7 w-7 text-primary-600"/>}/>
    <div className="sticky top-16 z-10 -mx-1 bg-[#F8FAFC]/95 px-1 pb-4 pt-1 backdrop-blur">
      <div className="relative"><Search className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} className="input h-12 pl-12 pr-4" placeholder="Pesquise: emitir boleto, cancelar nota, importar OFX..." aria-label="Pesquisar no tutorial"/></div>
      <div className="mt-3 flex gap-2 overflow-x-auto pb-1">{categories.map(item=><button type="button" key={item} onClick={()=>setCategory(item)} className={`shrink-0 rounded-lg border px-3 py-1.5 text-xs font-medium transition-colors ${category===item?'border-primary-600 bg-primary-600 text-white':'border-gray-200 bg-white text-gray-600 hover:border-primary-200 hover:text-primary-700'}`}>{item}</button>)}</div>
    </div>
    <div className="mt-4 grid gap-6 lg:grid-cols-[250px_minmax(0,1fr)]">
      <aside className="hidden lg:block"><div className="sticky top-48 border-l border-gray-200 pl-3"><p className="mb-2 px-2 text-xs font-semibold uppercase text-gray-400">{filtered.length} tema(s)</p>{filtered.map(guide=><a key={guide.id} href={`#${guide.id}`} className="flex items-center gap-1 rounded-md px-2 py-1.5 text-xs text-gray-600 transition-colors hover:bg-white hover:text-primary-700"><ChevronRight className="h-3 w-3 shrink-0"/><span className="line-clamp-2">{guide.title}</span></a>)}</div></aside>
      <section className="min-w-0 space-y-6">{filtered.length===0?<div className="rounded-lg border border-dashed border-gray-300 bg-white p-10 text-center"><Search className="mx-auto h-8 w-8 text-gray-300"/><p className="mt-3 font-medium text-gray-700">Nenhum tutorial encontrado</p><p className="mt-1 text-sm text-gray-500">Tente outro termo ou selecione Todos.</p></div>:filtered.map(guide=><article id={guide.id} key={guide.id} className="scroll-mt-48 overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm">
        <header className="border-b border-gray-100 px-5 py-4 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-xs font-semibold uppercase text-primary-600">{guide.category}</span><h2 className="mt-1 text-xl font-semibold text-gray-900">{guide.title}</h2><p className="mt-2 text-sm text-gray-600">{guide.summary}</p></div>{guide.route&&<Link to={guide.route} className="inline-flex items-center gap-1 rounded-lg border border-gray-200 px-3 py-2 text-xs font-medium text-gray-600 transition-colors hover:border-primary-200 hover:text-primary-700">Abrir módulo<ExternalLink className="h-3.5 w-3.5"/></Link>}</div></header>
        <div className="space-y-5 px-5 py-5 sm:px-6">{guide.prerequisites&&<div className="rounded-md border-l-4 border-blue-400 bg-blue-50 px-4 py-3"><p className="text-sm font-semibold text-blue-800">Antes de começar</p><ul className="mt-1 space-y-1 text-sm text-blue-700">{guide.prerequisites.map(item=><li key={item}>• {item}</li>)}</ul></div>}
          <div><h3 className="text-sm font-semibold text-gray-900">Passo a passo</h3><ol className="mt-3 space-y-3">{guide.steps.map((step,index)=><li key={step} className="flex gap-3 text-sm text-gray-700"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary-50 text-xs font-semibold text-primary-700">{index+1}</span><span className="pt-0.5 leading-5">{step}</span></li>)}</ol></div>
          <div className="flex gap-3 rounded-md bg-green-50 px-4 py-3"><Lightbulb className="mt-0.5 h-5 w-5 shrink-0 text-green-600"/><div><p className="text-sm font-semibold text-green-800">Resultado esperado</p><p className="mt-1 text-sm text-green-700">{guide.result}</p></div></div>
          {guide.notes&&<div className="flex gap-3 rounded-md bg-amber-50 px-4 py-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-600"/><div><p className="text-sm font-semibold text-amber-800">Atenção</p><ul className="mt-1 space-y-1 text-sm text-amber-700">{guide.notes.map(note=><li key={note}>• {note}</li>)}</ul></div></div>}
        </div>
      </article>)}</section>
    </div>
  </div>
}
